services:
    app:
        container_name: symfony
        build:
            context: .
            dockerfile: Dockerfile
        image: php83
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            PHP_OPCACHE_ENABLE: 1
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
            PHP_OPCACHE_MEMORY_CONSUMPTION: 192
            PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
        volumes:
            - ./:/var/www:rw
        networks:
            - api-network
    nginx:
        container_name: nginx-symfony
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./ssl:/etc/nginx/ssl
        networks:
            - api-network
    postgres:
        container_name: postgres
        image: postgres
        volumes:
            - "./docker/database/postgres/:/var/lib/postgresql/data/"
        environment:
            POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (useful to connect to the database)
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The PostgreSQL password (useful to connect to the database)
            POSTGRES_DB: ${POSTGRES_DB} # The PostgreSQL default database (automatically created at first launch)
        ports:
            - "5432:5432"
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
